Feature login
Juangr4/decide-single-LaMuela-1 pull request #9
Opened 2022-12-01 17:18 UTC by fravilpav

2022-12-03 11:07 UTC, josconsan1 approved these changes, later dismissed

2022-12-04 09:52 UTC, Juangr4 requested changes
Cambios a realizar antes de poder subirse:
1. Los archivos **data.db** no deben subirse.
2. Cambiar el método main de la clase **SQLMethods**.
3. Mejorar el código para que pase los tests de calidad de SonarCloud.

**Tienes que seguir la política de commits que tenemos establecida.**

2022-12-04 22:15 UTC, Juangr4 approved these changes

2022-12-04 22:21 UTC, josconsan1 approved these changes

2022-12-04 22:22 UTC, merged